### ISSUE TITLE
Security concern/risk: Keepassium requests too many privileges (full access) in OneDrive

### ISSUE THREAD

**Issue by slava-uxd** [keepassium/KeePassium#285]
**What can be improved?**
I was shocked when Mircosoft Authenticator showed this when I was adding OneDrive server connection:

> Have full access to all files you have access to
> KeePassium will be able to read, create, update and delete all OneDrive files that you can access.

This is an immediate red flag and a major security concern due to potential damage in case of a breach.

For its functionality KeePassium really only needs read, create, update and delete access on selected folder(s), where it can read/update the password database file and create/delete backups. There is absolutely no need to allow the app read, create, update and delete **all** OneDrive files.

**The solution you'd like**
According to [OneDirve API Docs](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/permissions_reference) a `Files.ReadWrite.AppFolder` privilege exists. Please use (or allow to choose) this option. Or find another way to downgrade the access privileges to folder level in order to enforce damage control in case of a breach.

**Alternatives you've considered**
Alternative solution is not to use Keepassium. We do not want this alternative.

**Comment by keepassium** [comment]
I guess this is settled, then.

**Comment by cedricdonie** [comment]
Hi, I hope that it's OK to comment on this issue again. As a user with a database on a personal OneDrive account, I would strongly favor`Files.ReadWrite.AppFolder` would as the default for the "+ > Connect to Server > OneDrive" (i.e., personal OneDrive) option.

It's a shame that this does not cover the corporate use-case. However, I am sure that there is a substantial user base with KBDX files on personal OneDrives. Windows 11 is tightly integrated with OneDrive and I expect that a substantial portion of Windows Keypass users with iPhones will have the same needs.

Shall we re-open this issue? I'm also happy to create a new issue.

**Comment by keepassium** [comment]
> However, I am sure that there is a substantial user base with KBDX files on personal OneDrives.

@cedricdonie , I would assume most OneDrive Personal users just don't care… And if `AppFolder` were to become the _default_ setting, this would definitely flood me with "it does not work" emails. That said, I am fine with offering `AppFolder` as an option.

There is also an idea (to be confirmed) how to limit the requested permissions for everyone, so yes, let's reopen.

**Comment by cedricdonie** [comment]
> > However, I am sure that there is a substantial user base with KBDX files on personal OneDrives.
> 
> @cedricdonie , I would assume most OneDrive Personal users just don't care…

It might be correct that (sadly) most personal users just don't care. Then again, a lot of KeePassium users will be security-concious and would not give any app access to all their documents which is a substantial risk for a breach.

> And if `AppFolder` were to become the _default_ setting, this would definitely flood me with "it does not work" emails. That said, I am fine with offering `AppFolder` as an option.

As an "advanced" or even somewhat hidden option would be fine for me. It didn't take long to find this GitHub issue via Google and I am sure that other users would also find it.

> There is also an idea (to be confirmed) how to limit the requested permissions for everyone, so yes, let's reopen.

That sounds great 👍. I would be fine with either limiting access to a single file or limiting access to a single folder (and optionally, subfolders recursively).

**Comment by n4imLess** [comment]
Are there any updates on this?

I've just migrated KeePass from DropBox to OneDrive and encountered this issue as well. I am on a Microsoft 365 Family Plan. Not really sure which type of OneDrive "subscription" this is, but I'd say "Personal". 

I don't use shared folders, neither any business use-cases. 

I'd really like to see a file only or folder only permission system or I might have to switch Cloud Provider (or App) again. 

Thanks.

**Comment by FranLa** [comment]
@keepassium Is there any progress regarding this issue ? As also somewhat mentioned above the problem could easily be solved by letting the users select the "cloud storage type" as separately selections - something like "OneDrive Personal" and "OneDrive Business" - and if the user selects "OneDrive Personal" you could use the "Files.ReadWrite.AppFolder" and if the user selects "OneDrive Business" you could (because of the mentioned problems) use "Files.ReadWrite.All" - i.e. you could handle "OneDrive Personal" and "OneDrive Business" as if they were totally different things (like if one of them were Google and the other one Dropbox)
What are your thoughts about that ?

**Comment by keepassium** [comment]
@FranLa , yes, this is the current plan: add "OneDrive Personal (app folder)" as a dedicated storage provider, alongside with "OneDrive Personal" and "OneDrive for Business". (Business OneDrive [does not](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/permissions_reference?view=odsp-graph-online#remarks) support app folder permission anyway.) 

That's why the issue remains open, but not exactly a priority, I'm afraid…

> There is also an idea (to be confirmed) how to limit the requested permissions for everyone, so yes, let's reopen.

The idea was to give KeePassium a direct link to the file (OneDrive app → file → Share → Copy link), so the app won't have to ask you to sign in and thus for any permissions at all. Unfortunately, sign-in is still [required](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/shares_get?view=odsp-graph-online#remarks) to work with these links, so that idea did not work out.

**Comment by FranLa** [comment]
Hi @keepassium Thank you for your reply. 

Even though this doesn't **exactly** match the subject of this thread (since it is about OneDrive access) I would like to add that after writing my comment here I decided to use keepassium with **Dropbox** instead.

And now I got even a **bigger** surprise: When I in the KeePassium app when choosing a cloud service used Dropbox I experienced the same problem/issue as with OneDrive: KeepPassium also requested access to the all files on Dropbox, not just the keepass related file(s)/folder.

As I on this particular Dropbox account didn't have anything 'confidential' I went ahead.

When I double checked via https://www.dropbox.com/account/connected_apps I could get confirmed, that keepassium in fact had access to all files - quote from this webpage under the 'KeePassium' > 'KeePassium labs' section:

Permissions | 
   - Edit content of your Dropbox files and folders and view content of your Dropbox files and folders
   - View basic information about your Dropbox account such as your username, email, and country


In contrast: I also use another app in the "KeePass family" (the Android app "Keepass2Android") where I also store the database on Dropbox (another Dropbox account). And here it is as expected: Keepass2Android has only requested (and received) the 'App folder' permission (=access to /Apps/Keepass2Android/*), which is reflected on this Dropbox account / url https://www.dropbox.com/home/Apps: Here in the  'Keepass2Android (App folder)' >  section I see the desired / 'correct' access (please notice the "only within the Apps › Keepass2Android folder"):

Permissions
    - Edit content of your Dropbox files and folders, view content of your Dropbox files and folders, and view and edit information about your Dropbox files and folders, **only within the Apps › Keepass2Android folder**
    - View basic information about your Dropbox account such as your username, email, and country

So my question is : I understand the problems with OneDrive as the OneDrive personal and OneDrive Business technically are somewhat different and at the moment treated as the same entry from the KeePassium app. 
But I don't understand why the Dropbox access requested by KeePassium isn't limited to the 'App folder' just like 'Keepass2Android' has implemented its access to the could storage?

I'm looking forward to read your comments

Thanks in advance
Frank

**Comment by keepassium** [comment]
> But I don't understand why the Dropbox access requested by KeePassium isn't limited to the 'App folder' just like 'Keepass2Android' has implemented its access to the could storage?

Let's imagine KeePassium can access only `/Apps/KeePassium`. But your database is in `/Apps/Keepass2Android`. What would be your next step?

**Comment by FranLa** [comment]
It isn't the same database, if that's what you meant. So I'm not trying to share the same database between KeePassium and Keepass2Android.

To be precise: The iphone / keepassium / dropbox setup is the one used by my girlfriend, and I'm using the Android / Keepass2Android / dropbox setup (and nobody - not even couples - should share their password manager contents :-) ). 

And I would NEVER buy an iPhone, and my girlfriend would NEVER buy an Android ;-)

But if you do expect that many users may want to share their keepass-databases (in the situation that only one of them is using KeePassium) you could in the keepassium app (**before** you initiate the oauth dialog (and then adjusted the oauth access-request to the users selection of access)) prompt your user which access they want to give keepassium to Dropbox:
1. access to all of the Dropbox files (to be able to share their keepass database even when that other person doesn't use keepassium)
2. only access to the Dropbox folder where they then would place their keepass database (/Apps/KeePassium/*)

That (if the user chooses the selection '1.' ) would of course also require that 'the other person' had to use the same Dropbox account.

If I personally wanted to access my database from more than one phone that other phone would for sure also be an Android (where I also would use keepass2android, so that wouldn't be a problem, since they both would use/access /Apps/Keepass2Android/*).

I *am* sharing my keepass database between the above android / keepass2android / dropbox database with my Windows PC by using the oriignal Windows KeePass application (and the Dropbox client on the same PC, pointing the Windows Keepass database at the Dropbox folder on my PC.

You could of course say that I'm letting the Windows Keepass application access all my Dropbox files - but the separation of Windows applications and most of the files on the Windows PC isn't as sophisticated / advanced as on iPhone and Android (where the data files of each application only are accessible to that app)  - so even if the Windows Keepass only had access to a specific dropbox folder via Oauth it still just could access the files in my local Dropbox folder.

**Comment by keepassium** [comment]
> you could in the keepassium app (…) prompt your user which access they want to give keepassium to Dropbox:

Well, that's what I said after "[yes, this is the current plan](https://github.com/keepassium/KeePassium/issues/285#issuecomment-2613367800)".

**Comment by FranLa** [comment]
Hi @keepassium . Ok, I read this "this is the current plan" as the plan just for OneDrive :-) 
But if the plans also include Dropbox I'm a happy camper - great !

Thanks for your comments and plan-information.  Keep up the good work 👍

**Comment by keepassium** [comment]
Good news, I can confirm that OneDrive access with app-folder scope is implemented for the upcoming v2.4.166.

**Comment by dimagohere** [comment]
I'm using v2.5.171 Pro and tried removing the OneDrive connection and adding again but still asking for full permission. Is this a bug now?

**Comment by keepassium** [comment]
@dimagohere , just to duplicate our email discussion here. 

The app-folder scope is listed separately, alongside with the full access option. To connect to OneDrive with reduced permissions, one has to specifically select the "App folder only" connection. The app folder is created on first connection and will be empty until you copy your database there.
